<div >
    <img src = "../banner/banner_ML_UNLP_1900_200.png" />
</div>

<a target="_blank" href="https://colab.research.google.com/github/ignaciomsarmiento/ML_UNLP_Lectures/blob/main/Week04/Notebook_SS04_clasification.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>



# XOR




q  | p | q v p 
---|---|------|
0 | 0 | 0 |
0 | 1 | 1 |
1 | 0 | 1 |
1 | 1 | 0 |


## Llamando las librerías

In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense

2023-11-29 18:16:14.766489: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Creamos las variables

In [2]:
X = np.array([
   [0, 0],
   [0, 1],
   [1, 0],
   [1, 1]
], 'float32')
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [3]:
X.shape

(4, 2)

In [4]:
y = np.array([
   [0],
   [1],
   [1],
   [0]
], 'float32')

y

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

## Entrenamos la red

In [5]:
# Use a sequential model with 2 hidden neurons, and 1 output neuron.
model = Sequential()
model.add(Dense(16, input_dim = 2, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

# Train model.
model.fit(X, y, batch_size = 1, epochs = 1000, verbose = 0)


In [6]:
# evaluamos el modelo
scores = model.evaluate(X, y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

1/1 [==============================] - 0s 133ms/step - loss: 0.0182 - binary_accuracy: 1.0000

binary_accuracy: 100.00%


## Resultados

In [7]:
print(model.predict(X).round())

1/1 [==============================] - 0s 57ms/step
[[0.]
 [1.]
 [1.]
 [0.]]
